#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

# Build gdscript.

env_gdscript = env_modules.Clone()

env_gdscript.Prepend(
    CPPEXTPATH=[
        "#thirdparty/wasmblr",
        "#thirdparty/wamr/core/iwasm/include",
    ]
)
env_gdscript.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_gdscript.add_source_files(env.modules_sources, "./editor/*.cpp")

    SConscript("editor/script_templates/SCsub")

    # Those two modules are required for the language server protocol
    if env["module_jsonrpc_enabled"] and env["module_websocket_enabled"]:
        env_gdscript.add_source_files(env.modules_sources, "./language_server/*.cpp")
    else:
        # Using a define in the disabled case, to avoid having an extra define
        # in regular builds where all modules are enabled.
        env_gdscript.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])
        # Also needed in main env to unexpose --lsp-port option.
        env.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])


if env["tests"]:
    env_gdscript.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gdscript.add_source_files(env.modules_sources, "./tests/*.cpp")

# Build wamr.

# if ARGUMENTS.get("gd", "") == "gd":
#     env_gdscript.Append(CPPDEFINES=["WASM_DISABLE"])
# gd_bench_count = ARGUMENTS.get("gdbench", "1")
# env_gdscript.Append(CPPDEFINES=[("GD_BENCH_COUNT", gd_bench_count)])

# Build wamr, based on modules/svg/SCsub.
env_wamr = env_modules.Clone()
wamr_dir = "#thirdparty/wamr/"
wamr_cpp_ext_path = [
    "core/iwasm/common",
    "core/iwasm/include",
    "core/iwasm/interpreter",
    "core/shared/mem-alloc",
    "core/shared/platform/include",
    "core/shared/utils",
]
env_arch = env_wamr["arch"]
env_platform = env_wamr["platform"]
wamr_fast = True
wamr_invoke_arch = True
wamr_defines = [
    "BH_FREE=wasm_runtime_free",
    "BH_MALLOC=wasm_runtime_malloc",
    "WASM_ENABLE_INTERP",
    "WASM_ENABLE_SIMD",
]
if wamr_fast:
    wamr_defines += [
        "WASM_ENABLE_FAST_INTERP",
    ]
env_wamr.Append(CPPDEFINES=wamr_defines)
wamr_sources = []
if env_platform == "linuxbsd":
    wamr_cpp_ext_path += ["core/shared/platform/linux"]
    wamr_sources += [
        "core/shared/platform/common/posix/posix_blocking_op.c",
        "core/shared/platform/common/posix/posix_malloc.c",
        "core/shared/platform/common/posix/posix_memmap.c",
        "core/shared/platform/common/posix/posix_thread.c",
        "core/shared/platform/common/posix/posix_time.c",
        "core/shared/platform/linux/platform_init.c",
    ]
env_wamr.Prepend(CPPEXTPATH=[wamr_dir + wamr_path for wamr_path in wamr_cpp_ext_path])
wamr_sources += [
    "core/shared/mem-alloc/ems/ems_alloc.c",
    "core/shared/mem-alloc/ems/ems_kfc.c",
    "core/shared/mem-alloc/mem_alloc.c",
    "core/shared/platform/common/memory/mremap.c",
    "core/shared/utils/bh_common.c",
    "core/shared/utils/bh_list.c",
    "core/shared/utils/bh_log.c",
    "core/shared/utils/bh_leb128.c",
    "core/shared/utils/bh_vector.c",
    "core/shared/utils/runtime_timer.c",
    "core/iwasm/common/wasm_c_api.c",
    "core/iwasm/common/wasm_exec_env.c",
    "core/iwasm/common/wasm_loader_common.c",
    "core/iwasm/common/wasm_memory.c",
    "core/iwasm/common/wasm_native.c",
    "core/iwasm/common/wasm_runtime_common.c",
    "core/iwasm/interpreter/wasm_loader.c",
    "core/iwasm/interpreter/wasm_mini_loader.c",
    "core/iwasm/interpreter/wasm_runtime.c",
]
if wamr_invoke_arch:
    if env_arch == "x86_64":
        wamr_sources += [
            "core/iwasm/common/arch/invokeNative_em64_simd.s",
        ]
else:
    wamr_sources += [
        "core/iwasm/common/arch/invokeNative_general.c",
    ]
if wamr_fast:
    wamr_sources += [
        "core/iwasm/interpreter/wasm_interp_fast.c",
    ]
else:
    wamr_sources += [
        "core/iwasm/interpreter/wasm_interp_classic.c",
    ]
wamr_sources = [wamr_dir + wamr_source for wamr_source in wamr_sources]
env_wamr.add_source_files(env.modules_sources, wamr_sources)
# env.Depends(wamr_obj)
